name: Build C++

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    
    - name: Compile for Windows
      run: |
        g++ src/epi.cpp -o epi2.exe icon/icon.o -static -lwinmm -lole32 -lgdi32 -lwinspool -lwlanapi -lWs2_32 -lwininet -lwinhttp -liphlpapi -lurlmon -lcomctl32 
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: |
          epi2.exe

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile for Linux
        run: |
          # Update apt-get and install required libraries
          sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev
          
          # Create output folder
          mkdir linux-target
          
          # Comile program using g++
          g++ src/epi.cpp -o linux-target/epi2 -lncurses -lcurl

      - name: Upload executables
        uses: actions/upload-artifact@v4
        with:
          name: linux-executable
          path: |
            linux-target/epi2
