name: Build C++

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    
    - name: Compile for Windows
      run: |
        g++ nt-tablas.cpp -o nt-tablas -static -lgdi32 -lwinspool
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: |
          nt-tablas.exe

